version: '3.8'

services:
  db:
    image: postgres:16
    container_name: blog-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - blog-network

  # 2. BACKEND (Spring Boot)
  backend:
    build: ./blogmanagement
    container_name: blog-backend
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: http://localhost:5173 
      BACKEND_URL: http://localhost:8080
    volumes:
      - ./uploads:/app/uploads 
    depends_on:
      - db
    networks:
      - blog-network

  # 3. FRONTEND (React + Nginx)
  frontend:
    build:
      context: ./blog-frontend
      args:
        VITE_API_URL: http://localhost:8080/api
    container_name: blog-frontend
    ports:
      - "5173:80" 
    depends_on:
      - backend
    networks:
      - blog-network

volumes:
  postgres_data:

networks:
  blog-network:
    driver: bridge